# Generated by Django 3.2.12 on 2024-04-21 11:47

import blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[blog.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 21, 11, 47, 54, 125663)),
        ),
    ]
